# DICE
kind: Pod
apiVersion: v1
metadata:
  name: dice-app
  labels:
    app: dice
spec:
  containers:
    - name: dice-app
      image: dice-container
      imagePullPolicy: Never
---
kind: Service
apiVersion: v1
metadata:
  name: dice-service
spec:
  type: NodePort
  selector:
    app: dice
  ports:
    - port: 5000
---
# GREET
kind: Pod
apiVersion: v1
metadata:
  name: greet-app
  labels:
    app: greet
spec:
  containers:
    - name: greet-app
      image: greet-container
      imagePullPolicy: Never
---
kind: Service
apiVersion: v1
metadata:
  name: greet-service
spec:
  type: NodePort
  selector:
    app: greet
  ports:
    - port: 5000
---
# TIMESTAMP
kind: Pod
apiVersion: v1
metadata:
  name: timestamp-app
  labels:
    app: timestamp
spec:
  containers:
    - name: timestamp-app
      image: timestamp-container
      imagePullPolicy: Never
---
kind: Service
apiVersion: v1
metadata:
  name: timestamp-service
spec:
  type: NodePort
  selector:
    app: timestamp
  ports:
    - port: 5000
---
# INPUT VALIDATE
kind: Pod
apiVersion: v1
metadata:
  name: input-validate-app
  labels:
    app: input-validate
spec:
  containers:
    - name: input-validate-app
      image: input-validate-container
      imagePullPolicy: Never
---
kind: Service
apiVersion: v1
metadata:
  name: input-validate-service
spec:
  type: NodePort
  selector:
    app: input-validate
  ports:
    - port: 5000
---
# CALCULATE
kind: Pod
apiVersion: v1
metadata:
  name: calculate-app
  labels:
    app: calculate
spec:
  containers:
    - name: calculate-app
      image: calculate-container
      imagePullPolicy: Never
---
kind: Service
apiVersion: v1
metadata:
  name: calculate-service
spec:
  type: NodePort
  selector:
    app: calculate
  ports:
    - port: 5000
---
# FORMAT OUTPUT
kind: Pod
apiVersion: v1
metadata:
  name: format-output-app
  labels:
    app: format-output
spec:
  containers:
    - name: format-output-app
      image: format-output-container
      imagePullPolicy: Never
---
kind: Service
apiVersion: v1
metadata:
  name: format-output-service
spec:
  type: NodePort
  selector:
    app: format-output
  ports:
    - port: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
  annotations:
    nging.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: kube.info
    http:
        paths:
          # Use regex to allow specifying params / subpaths
          # - pathType: ImplementationSpecific
          #   path: /noncomm/dice(/|$)(.*)
          #   backend:
          #     service:
          #       name: dice-service
          #       port:
          #         number: 5000

          # Non-communicating
          - pathType: Prefix
            path: /
            backend:
              service:
                name: greet-service
                port:
                  number: 5000
          - pathType: Prefix
            path: /noncomm/dice_roll
            backend:
              service:
                name: dice-service
                port:
                  number: 5000
          - pathType: Prefix
            path: /noncomm/greetings
            backend:
              service:
                name: greet-service
                port:
                  number: 5000

          - pathType: Prefix
            path: /noncomm/timestamp
            backend:
              service:
                name: timestamp-service
                port:
                  number: 5000


          # Communicating
          - pathType: ImplementationSpecific
            path: /comm/increment
            backend:
              service:
                name: input-validate-service
                port:
                  number: 5000

          - pathType: ImplementationSpecific
            path: /comm/inc-calculate
            backend:
              service:
                name: calculate-service
                port:
                  number: 5000

          - pathType: ImplementationSpecific
            path: /comm/inc-format-output
            backend:
              service:
                name: format-output-service
                port:
                  number: 5000
---
